import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Header from "./Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="body bg-[#343542] w-screen h-full">
        {/* Header */}
        <Header />
        {/* ChatLog */}
        <div className="flex flex-col space-y-2 p-2">
          <div className="chat-box-left">Hey I'm a robot BEEP BOOP</div>
          <div className="chat-box-left">
            I'm a robot and I can do whatever you waht, ask me something go
            ahead, ask me ask me ask me
          </div>
          <div className="chat-box-right">
            ullamcorper, sollicitudin leo vitae, egestas elit. Nulla tristique
            sed lectus eu eleifend. Morbi facilisis nunc turpis, vel iaculis
            justo viverra quis. Pellentesque feugiat velit sed risus interdum,
            vel maximus purus gravida.
          </div>
          <div className="chat-box-right">
            eros urna rhoncus risus, vitae ultricies nibh diam sit amet tortor.
            Sed congue justo eget consectetur fermentum. Nam commodo velit sed
            cursus blandit.
          </div>
          <div className="chat-box-left">
            Fusce pretium nisl a luctus dapibus. Vivamus efficitur tellus ac
            dolor tincidunt tempus. Vestibulum ante ipsum primis in faucibus
            orci luctus et ultrices posuere cubilia curae; In vel justo lectus.
            Vestibulum eget odio nisi. Curabitur ac mi sed ante luctus dictum.
            Cras et auctor nisi, sit amet malesuada dolor.
          </div>
          <div className="chat-box-right">
            Bing Bong
          </div>
          <div className="chat-box-left">
            Fusce pretium nisl a luctus dapibus. Vivamus efficitur tellus ac
            dolor tincidunt tempus. Vestibulum ante ipsum primis in faucibus
            orci luctus et ultrices posuere cubilia curae;
          </div>
        </div>
        {/* ChatInput */}
      </div>
    </>
  );
}
