import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Header from "./Header";
import ChatLog from "./ChatLog";
import ChatInput from "./ChatInput";
import { useState, useRef } from "react";

export default function Home() {
  const sectionRef = useRef(null);
  const [input, setInput] = useState("");
  const [chatLog, setChatLog] = useState([
    {
      user: "gbt",
      message: "GM GM",
    },
    {
      user: "gbt",
      message: "I'm a AI Robot.. Beep Boop",
    },
    {
      user: "gbt",
      message: "How can I help you today?",
    },
  ]);

  function clearChat() {
    setChatLog([]);
  }

  function scrollToBottom() {
    console.log("scrolling");
    sectionRef.current.scrollIntoView({ behavior: "smooth", block: "end" });
  }

  async function handleSubmit(e) {
    e.preventDefault();
    console.log("submit");
    let chatLogNew = [...chatLog, { user: "me", message: `${input}` }];
    await setInput("");
    const messages = chatLogNew.map((message) => message.message).join("\n");
    const response = await fetch("http://localhost:3080/", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        message: messages,
      }),
    });
    const data = await response.json();
    await setChatLog([
      ...chatLogNew,
      { user: "gbt", message: `${data.message}` },
    ]);
    console.log(data.message);
    scrollToBottom();
  }

  return (
    <>
      <Head>
        <title>Beep Boop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="body bg-[#343542] w-screen min-h-screen">
        {/* Header */}
        <div className="headerContainer h-10 w-screen bg-[#343542] border-b-2 border-[#5F646C] flex justify-between p-2 fixed top-0 z-10">
          <div className="headerIconTwo">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              strokeWidth={1.5}
              stroke="currentColor"
              className="w-6 h-6"
              onClick={clearChat}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0"
              />
            </svg>
          </div>
          <div className="headerText">
            <h1>Beep Boop Chat</h1>
          </div>
          <div className="headerIconTwo">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              strokeWidth={1.5}
              stroke="currentColor"
              className="w-6 h-6"
              onClick={scrollToBottom}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M9 12.75l3 3m0 0l3-3m-3 3v-7.5M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
              />
            </svg>
          </div>
        </div>
        {/* ChatLog */}
        <div className="w-screen flex flex-col space-y-2 p-2 mt-10 mb-10">
          {chatLog.map((message, index) => (
            <ChatMessage key={index} message={message} />
          ))}
          <br/>
          <br/>
          <br/>
          <br/>
          <br/>
          <br/>
          <br/>
          <br/>
          <br/>
          <div className="h-10" ref={sectionRef}></div>
        </div>
        {/* ChatInput */}
        <div className="chatInputContainer h-20 w-screen border-t-2 bg-[#343542] border-[#5F646C] flex justify-center fixed bottom-0 z-10">
          <div className="flex mt-5 mr-5 ml-5 w-full h-fit justify-center">
            <form className="w-full" onSubmit={handleSubmit}>
              <input
                className="h-10 w-full appearance-none rounded p-2 text-white bg-[#40414f] outline-none"
                id="username"
                type="text"
                placeholder="Ask me a something"
                autoComplete="off"
                rows="1"
                value={input}
                onChange={(e) => setInput(e.target.value)}
              />
            </form>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              strokeWidth={1.5}
              stroke="currentColor"
              className="w-9 h-9 ml-2"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z"
              />
            </svg>
          </div>
        </div>
        <br />
        <br />
      </div>
    </>
  );
}

const ChatMessage = ({ message }) => {
  return (
    <div
      className={message.user === "gbt" ? "chat-box-left" : "chat-box-right"}
    >
      <div className={message.user === "gbt" ? "pl-4" : "pr-4"}>
        {message.message}
      </div>
    </div>
  );
};
